[build]
  base = "mindwatch-frontend"
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "../mindwatch-backend"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/netlify-api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
